### ISSUE TITLE
图像存档位置不合理

### ISSUE THREAD

**Issue by optdesigns** [xzhuah/NodeTreeStore#2]
Python: Traceback (most recent call last):
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MACHIN3tools\ui\operators\save.py", line 51, in execute
    bpy.ops.wm.save_mainfile()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: 错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\Fingerprints new small.jpg'
错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\Fingerprints new small.jpg'
错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\scratches big 1k.jpg'
错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\scratches big 1k.jpg'
错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\Seamless metal scratches.jpg'
错误: 无法打包文件,找不到资源路径 'Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images\Seamless metal scratches.jpg'

上面的错误是由于我把插件数据文件夹换了位置挪到了x盘，但是节点数据并不会及时更改，建议节点存储时路径使用插件设置里的节点保存路径 不然挪动文件节点里的图像都会找不到路径

**Comment by xzhuah** [comment]
根据你的错误信息，你所看到的错误并不是来自节点树仓库插件，而是来自一个叫MACHIN3tools的插件。

节点树仓库插件在设计时是考虑了用户更改节点存储路径的情况的，在加载节点树中的图片时，插件按照以下顺序寻找图片

1. 检查当前项目中已经加载的图片，是否存在与Json节点文件中的图片路径相同的图片，如果有则直接使用
2. 检查Json节点文件中的图片路径是否有效，如果图片存在于该目录下，则加载该图片
3. 如果Json节点文件中的图片路径失效，则尝试在插件设置的节点保存路径下的images文件夹中寻找同名图片进行加载
4. 如果仍然无法找到图片，则插件会创建一个空的图片节点，但并不会报错。

如果你移动了插件数据文件夹，只需要在插件设置中更新节点保存路径 ，插件应当可以正常加载图片。你所看到的错误信息是由
MACHIN3tools插件引起的，可能的原因是你的Blender项目中已经保存了一些引用了外部资源的节点，没有打包到项目中，当你移动外部资源文件后，这些节点仍然试图引用原先的资源，因而产生了异常。由于这些资源刚好保存在了节点树仓库的路径下，可能会让人误以为是节点树仓库造成的错误。

建议你可以尝试如下解决方案
1. 将缺失的图片资源复制到 “Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images”路径下
2. 打开你的项目，选择 文件->外部数据->勾选自动打包资源，保存项目
3. 选择 文件->清理->递归未使用的关联数据块
4. 保存项目

完成这些步骤后你的图片应该已经被打包到你的项目中了，
之后你可以删除 “Y:\Program Files\Blender Foundation\NodeTreeStore\3.6\images，来观察你的项目是否可以正常显示
