### ISSUE TITLE
功能建议：批量添加节点树插件

### ISSUE THREAD

**Issue by 1067237855** [xzhuah/NodeTreeStore#3]
大佬的插件非常好用，在这里有个小建议，希望大佬能够考虑一下

## 目的：
别人分享的节点树，我希望导入到“[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)”插件中，方便以后调用
## 遇到的问题：
别人分享的节点树（几百个节点），每一个都需要重复以下操作：翻译、保存、命名、备注等多个步操作，然后才能添加节点到[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)中。
翻译节点组（Erindale Toolkit翻译问题）：别人分享的资产如果能够够批量翻译一下是最好的了，具体参考“翻译节点组”插件中的批量翻译功能  https://www.bilibili.com/video/BV1tM4y1y7yr/?spm_id_from=333.337.search-card.all.click

## 理想的状态：
别人分享的节点（例如：[Erindale Toolkit](https://blenderco.cn/35427.html)）→→→[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)能够**批量翻译**节点→→→然后**批量添加**到自己的[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)节点库中

## 现在的状态：
别人分享的节点（例如：[Erindale Toolkit](https://blenderco.cn/35427.html)）→→→在“翻译节点组”插件中翻译→→→切换到[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)插件，几百个节点手动逐个添加节点到[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)中，每一个都需要重复以下操作：翻译、保存、命名、备注等多个步操作，然后才能添加节点到[NodeTreeStore](https://github.com/xzhuah/NodeTreeStore)中。

![image](https://github.com/xzhuah/NodeTreeStore/assets/104330036/22d89632-416f-4a0c-b609-f42b7456dd27)

![image](https://github.com/xzhuah/NodeTreeStore/assets/104330036/5c2a9ead-ef26-46f7-9b71-e9709d2a8c1e)

**Comment by 1067237855** [comment]
![image](https://github.com/xzhuah/NodeTreeStore/assets/104330036/173df734-6f76-4356-a26f-1151072726e1)

**Comment by 1067237855** [comment]
别人分享的节点（例如：[Erindale Toolkit](https://blenderco.cn/35427.html)）

链接: https://pan.baidu.com/s/1TlTiw4oSBjhVgIXL9HZZ5A?pwd=wv3g 提取码: wv3g 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by xzhuah** [comment]
感谢您的建议，我决定优先为插件添加批量保存选中的节点组的功能。

对于翻译功能，我需要进一步调研，不过毕竟有别的插件可以方便准确地完成批量翻译，这项需求的优先度我会降低。

对于搜索功能，这是一个非常不错的建议，但是有一定的开发难度，事实上这不单单是一个搜索的功能，而是需要一整套搜索->选择->加载的用户流程，需要引入新的UI面板和用户逻辑，开发难度稍大。我会延后安排这项功能

**Comment by xzhuah** [comment]
批量添加节点组的功能已经添加：【Blender 批量保存复用节点组】 https://www.bilibili.com/video/BV1qu41137V7/?share_source=copy_web&vd_source=274308cad241acba810d206ac5a69844
